/**
 * CORRECCIÓN ORTOGRÁFICA EN ESPAÑOL
 *
 * Criterio de seguridad: solo se corrigen palabras que SIN tilde o SIN eñe
 * no existen en español. Por eso NO se tocan "mas", "el", "tu", "si", "se",
 * "esta", "como", "solo"... que son palabras válidas y cambiarlas arruinaría
 * el texto. Tampoco se corrige la palabra que se está escribiendo: solo la
 * anterior, cuando ya se escribió un espacio o un signo de puntuación.
 */

const CORRECCIONES: Record<string, string> = {
  accion: "acción",
  ademas: "además",
  adios: "adiós",
  adonde: "adónde",
  ambiguedad: "ambigüedad",
  ambito: "ámbito",
  analisis: "análisis",
  angel: "ángel",
  animo: "ánimo",
  anio: "año",
  anios: "años",
  aqui: "aquí",
  arbol: "árbol",
  articulo: "artículo",
  asi: "así",
  atencion: "atención",
  autobus: "autobús",
  avion: "avión",
  banio: "baño",
  buenisimo: "buenísimo",
  cafe: "café",
  calificacion: "calificación",
  camara: "cámara",
  cancion: "canción",
  capitan: "capitán",
  caracter: "carácter",
  celebracion: "celebración",
  clasico: "clásico",
  codigo: "código",
  comite: "comité",
  companera: "compañera",
  companeras: "compañeras",
  companero: "compañero",
  companeros: "compañeros",
  compania: "compañía",
  comun: "común",
  comunicacion: "comunicación",
  condicion: "condición",
  conexion: "conexión",
  consideracion: "consideración",
  construccion: "construcción",
  cortesia: "cortesía",
  credito: "crédito",
  cumpleanos: "cumpleaños",
  danio: "daño",
  decision: "decisión",
  demas: "demás",
  democratico: "democrático",
  descripcion: "descripción",
  despues: "después",
  dia: "día",
  diagnostico: "diagnóstico",
  dificil: "difícil",
  direccion: "dirección",
  disenar: "diseñar",
  diseno: "diseño",
  distribucion: "distribución",
  division: "división",
  documentacion: "documentación",
  economia: "economía",
  edicion: "edición",
  educacion: "educación",
  ejercito: "ejército",
  eleccion: "elección",
  electronico: "electrónico",
  energia: "energía",
  enfasis: "énfasis",
  ensenanza: "enseñanza",
  ensenar: "enseñar",
  epoca: "época",
  espanol: "español",
  espanola: "española",
  espectaculo: "espectáculo",
  estara: "estará",
  esten: "estén",
  estimulo: "estímulo",
  evaluacion: "evaluación",
  examenes: "exámenes",
  exito: "éxito",
  explicacion: "explicación",
  exposicion: "exposición",
  extranio: "extraño",
  fabrica: "fábrica",
  facil: "fácil",
  fantastico: "fantástico",
  fisica: "física",
  formacion: "formación",
  fotografia: "fotografía",
  funcion: "función",
  geografia: "geografía",
  gestion: "gestión",
  grafico: "gráfico",
  guia: "guía",
  habia: "había",
  habil: "hábil",
  identificacion: "identificación",
  imagenes: "imágenes",
  importantisimo: "importantísimo",
  impresion: "impresión",
  informacion: "información",
  informatica: "informática",
  ingles: "inglés",
  institucion: "institución",
  instruccion: "instrucción",
  interes: "interés",
  invitacion: "invitación",
  jardin: "jardín",
  jovenes: "jóvenes",
  lapiz: "lápiz",
  lider: "líder",
  limite: "límite",
  linea: "línea",
  logica: "lógica",
  maestria: "maestría",
  manana: "mañana",
  maniana: "mañana",
  maquina: "máquina",
  matematica: "matemática",
  matematicas: "matemáticas",
  maximo: "máximo",
  medico: "médico",
  metodo: "método",
  minimo: "mínimo",
  modulo: "módulo",
  motivacion: "motivación",
  munieco: "muñeco",
  musica: "música",
  nacion: "nación",
  nina: "niña",
  ninas: "niñas",
  nino: "niño",
  ninos: "niños",
  numero: "número",
  observacion: "observación",
  obtencion: "obtención",
  ocasion: "ocasión",
  opcion: "opción",
  operacion: "operación",
  organizacion: "organización",
  otono: "otoño",
  oxigeno: "oxígeno",
  pagina: "página",
  parrafo: "párrafo",
  participacion: "participación",
  pedagogia: "pedagogía",
  peliculas: "películas",
  pequena: "pequeña",
  pequenas: "pequeñas",
  pequeno: "pequeño",
  pequenos: "pequeños",
  periodico: "periódico",
  platica: "plática",
  poesia: "poesía",
  politica: "política",
  practica: "práctica",
  preparacion: "preparación",
  presentacion: "presentación",
  problematica: "problemática",
  produccion: "producción",
  programacion: "programación",
  proposito: "propósito",
  proximo: "próximo",
  publico: "público",
  quimica: "química",
  rapido: "rápido",
  razon: "razón",
  recepcion: "recepción",
  reflexion: "reflexión",
  region: "región",
  relacion: "relación",
  religion: "religión",
  reunion: "reunión",
  revision: "revisión",
  sabado: "sábado",
  salon: "salón",
  sancion: "sanción",
  seccion: "sección",
  segun: "según",
  seleccion: "selección",
  senor: "señor",
  senora: "señora",
  senores: "señores",
  senorita: "señorita",
  sesion: "sesión",
  simbolo: "símbolo",
  sintesis: "síntesis",
  situacion: "situación",
  sueno: "sueño",
  suenos: "sueños",
  supervision: "supervisión",
  tambien: "también",
  tecnica: "técnica",
  tecnico: "técnico",
  telefono: "teléfono",
  television: "televisión",
  tematica: "temática",
  teoria: "teoría",
  termino: "término",
  titulo: "título",
  tradicion: "tradición",
  traves: "través",
  ultimo: "último",
  unico: "único",
  union: "unión",
  utiles: "útiles",
  valoracion: "valoración",
  version: "versión",
};

/** Copia el uso de mayúsculas de la palabra original. */
function conMismaForma(original: string, corregida: string): string {
  if (original === original.toUpperCase()) return corregida.toUpperCase();
  if (original[0] === original[0]?.toUpperCase()) {
    return corregida[0].toUpperCase() + corregida.slice(1);
  }
  return corregida;
}

/**
 * Corrige las palabras ya terminadas de un texto.
 * La última palabra se deja intacta mientras se está escribiendo.
 */
export function autocorregir(texto: string): string {
  return texto.replace(
    /([A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)(?=[\s.,;:!?¡¿()\[\]"'\u2013\u2014/-])/g,
    (palabra) => {
      const arreglo = CORRECCIONES[palabra.toLowerCase()];
      return arreglo ? conMismaForma(palabra, arreglo) : palabra;
    }
  );
}

/** Corrige el texto completo, incluida la última palabra. Para usar al guardar. */
export function autocorregirFinal(texto: string): string {
  return autocorregir(texto + " ").slice(0, -1);
}

/** Cuántas palabras corregiría, sin modificar nada. Útil para avisar. */
export function contarCorrecciones(texto: string): number {
  const antes = texto;
  const despues = autocorregirFinal(texto);
  if (antes === despues) return 0;
  const a = antes.split(/\s+/);
  const b = despues.split(/\s+/);
  return a.reduce((n, palabra, i) => (palabra !== b[i] ? n + 1 : n), 0);
}
